export const Currency = [
  {
    currency: "Albania Lek",
    abbreviation: "ALL",
    symbol: "Lek",
  },
  {
    currency: "Afghanistan Afghani",
    abbreviation: "AFN",
    symbol: "؋",
  },
  {
    currency: "Argentina Peso",
    abbreviation: "ARS",
    symbol: "$",
  },
  {
    currency: "Aruba Guilder",
    abbreviation: "AWG",
    symbol: "ƒ",
  },
  {
    currency: "Australia Dollar",
    abbreviation: "AUD",
    symbol: "$",
  },
  {
    currency: "Azerbaijan New Manat",
    abbreviation: "AZN",
    symbol: "ман",
  },
  {
    currency: "Bahamas Dollar",
    abbreviation: "BSD",
    symbol: "$",
  },
  {
    currency: "Barbados Dollar",
    abbreviation: "BBD",
    symbol: "$",
  },
  {
    currency: "Belarus Ruble",
    abbreviation: "BYR",
    symbol: "p.",
  },
  {
    currency: "Belize Dollar",
    abbreviation: "BZD",
    symbol: "BZ$",
  },
  {
    currency: "Bermuda Dollar",
    abbreviation: "BMD",
    symbol: "$",
  },
  {
    currency: "Bolivia Boliviano",
    abbreviation: "BOB",
    symbol: "$b",
  },
  {
    currency: "Bosnia and Herzegovina Convertible Marka",
    abbreviation: "BAM",
    symbol: "KM",
  },
  {
    currency: "Botswana Pula",
    abbreviation: "BWP",
    symbol: "P",
  },
  {
    currency: "Bulgaria Lev",
    abbreviation: "BGN",
    symbol: "лв",
  },
  {
    currency: "Brazil Real",
    abbreviation: "BRL",
    symbol: "R$",
  },
  {
    currency: "Brunei Darussalam Dollar",
    abbreviation: "BND",
    symbol: "$",
  },
  {
    currency: "Cambodia Riel",
    abbreviation: "KHR",
    symbol: "៛",
  },
  {
    currency: "Canada Dollar",
    abbreviation: "CAD",
    symbol: "$",
  },
  {
    currency: "Cayman Islands Dollar",
    abbreviation: "KYD",
    symbol: "$",
  },
  {
    currency: "Chile Peso",
    abbreviation: "CLP",
    symbol: "$",
  },
  {
    currency: "China Yuan Renminbi",
    abbreviation: "CNY",
    symbol: "¥",
  },
  {
    currency: "Colombia Peso",
    abbreviation: "COP",
    symbol: "$",
  },
  {
    currency: "Costa Rica Colon",
    abbreviation: "CRC",
    symbol: "₡",
  },
  {
    currency: "Croatia Kuna",
    abbreviation: "HRK",
    symbol: "kn",
  },
  {
    currency: "Cuba Peso",
    abbreviation: "CUP",
    symbol: "₱",
  },
  {
    currency: "Czech Republic Koruna",
    abbreviation: "CZK",
    symbol: "Kč",
  },
  {
    currency: "Denmark Krone",
    abbreviation: "DKK",
    symbol: "kr",
  },
  {
    currency: "Dominican Republic Peso",
    abbreviation: "DOP",
    symbol: "RD$",
  },
  {
    currency: "East Caribbean Dollar",
    abbreviation: "XCD",
    symbol: "$",
  },
  {
    currency: "Egypt Pound",
    abbreviation: "EGP",
    symbol: "£",
  },
  {
    currency: "El Salvador Colon",
    abbreviation: "SVC",
    symbol: "$",
  },
  {
    currency: "Estonia Kroon",
    abbreviation: "EEK",
    symbol: "kr",
  },
  {
    currency: "Euro Member Countries",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    currency: "Falkland Islands (Malvinas) Pound",
    abbreviation: "FKP",
    symbol: "£",
  },
  {
    currency: "Fiji Dollar",
    abbreviation: "FJD",
    symbol: "$",
  },
  {
    currency: "Ghana Cedis",
    abbreviation: "GHC",
    symbol: "¢",
  },
  {
    currency: "Gibraltar Pound",
    abbreviation: "GIP",
    symbol: "£",
  },
  {
    currency: "Guatemala Quetzal",
    abbreviation: "GTQ",
    symbol: "Q",
  },
  {
    currency: "Guernsey Pound",
    abbreviation: "GGP",
    symbol: "£",
  },
  {
    currency: "Guyana Dollar",
    abbreviation: "GYD",
    symbol: "$",
  },
  {
    currency: "Honduras Lempira",
    abbreviation: "HNL",
    symbol: "L",
  },
  {
    currency: "Hong Kong Dollar",
    abbreviation: "HKD",
    symbol: "$",
  },
  {
    currency: "Hungary Forint",
    abbreviation: "HUF",
    symbol: "Ft",
  },
  {
    currency: "Iceland Krona",
    abbreviation: "ISK",
    symbol: "kr",
  },
  {
    currency: "India Rupee",
    abbreviation: "INR",
    symbol: "₹",
  },
  {
    currency: "Indonesia Rupiah",
    abbreviation: "IDR",
    symbol: "Rp",
  },
  {
    currency: "Iran Rial",
    abbreviation: "IRR",
    symbol: "﷼",
  },
  {
    currency: "Isle of Man Pound",
    abbreviation: "IMP",
    symbol: "£",
  },
  {
    currency: "Israel Shekel",
    abbreviation: "ILS",
    symbol: "₪",
  },
  {
    currency: "Jamaica Dollar",
    abbreviation: "JMD",
    symbol: "J$",
  },
  {
    currency: "Japan Yen",
    abbreviation: "JPY",
    symbol: "¥",
  },
  {
    currency: "Jersey Pound",
    abbreviation: "JEP",
    symbol: "£",
  },
  {
    currency: "Kazakhstan Tenge",
    abbreviation: "KZT",
    symbol: "лв",
  },
  {
    currency: "Korea (North) Won",
    abbreviation: "KPW",
    symbol: "₩",
  },
  {
    currency: "Korea (South) Won",
    abbreviation: "KRW",
    symbol: "₩",
  },
  {
    currency: "Kyrgyzstan Som",
    abbreviation: "KGS",
    symbol: "лв",
  },
  {
    currency: "Laos Kip",
    abbreviation: "LAK",
    symbol: "₭",
  },
  {
    currency: "Latvia Lat",
    abbreviation: "LVL",
    symbol: "Ls",
  },
  {
    currency: "Lebanon Pound",
    abbreviation: "LBP",
    symbol: "£",
  },
  {
    currency: "Liberia Dollar",
    abbreviation: "LRD",
    symbol: "$",
  },
  {
    currency: "Lithuania Litas",
    abbreviation: "LTL",
    symbol: "Lt",
  },
  {
    currency: "Macedonia Denar",
    abbreviation: "MKD",
    symbol: "ден",
  },
  {
    currency: "Malaysia Ringgit",
    abbreviation: "MYR",
    symbol: "RM",
  },
  {
    currency: "Mauritius Rupee",
    abbreviation: "MUR",
    symbol: "₨",
  },
  {
    currency: "Mexico Peso",
    abbreviation: "MXN",
    symbol: "$",
  },
  {
    currency: "Mongolia Tughrik",
    abbreviation: "MNT",
    symbol: "₮",
  },
  {
    currency: "Mozambique Metical",
    abbreviation: "MZN",
    symbol: "MT",
  },
  {
    currency: "Namibia Dollar",
    abbreviation: "NAD",
    symbol: "$",
  },
  {
    currency: "Nepal Rupee",
    abbreviation: "NPR",
    symbol: "₨",
  },
  {
    currency: "Netherlands Antilles Guilder",
    abbreviation: "ANG",
    symbol: "ƒ",
  },
  {
    currency: "New Zealand Dollar",
    abbreviation: "NZD",
    symbol: "$",
  },
  {
    currency: "Nicaragua Cordoba",
    abbreviation: "NIO",
    symbol: "C$",
  },
  {
    currency: "Nigeria Naira",
    abbreviation: "NGN",
    symbol: "₦",
  },
  {
    currency: "Korea (North) Won",
    abbreviation: "KPW",
    symbol: "₩",
  },
  {
    currency: "Norway Krone",
    abbreviation: "NOK",
    symbol: "kr",
  },
  {
    currency: "Oman Rial",
    abbreviation: "OMR",
    symbol: "﷼",
  },
  {
    currency: "Pakistan Rupee",
    abbreviation: "PKR",
    symbol: "₨",
  },
  {
    currency: "Panama Balboa",
    abbreviation: "PAB",
    symbol: "B/.",
  },
  {
    currency: "Paraguay Guarani",
    abbreviation: "PYG",
    symbol: "Gs",
  },
  {
    currency: "Peru Nuevo Sol",
    abbreviation: "PEN",
    symbol: "S/.",
  },
  {
    currency: "Philippines Peso",
    abbreviation: "PHP",
    symbol: "₱",
  },
  {
    currency: "Poland Zloty",
    abbreviation: "PLN",
    symbol: "zł",
  },
  {
    currency: "Qatar Riyal",
    abbreviation: "QAR",
    symbol: "﷼",
  },
  {
    currency: "Romania New Leu",
    abbreviation: "RON",
    symbol: "lei",
  },
  {
    currency: "Russia Ruble",
    abbreviation: "RUB",
    symbol: "руб",
  },
  {
    currency: "Saint Helena Pound",
    abbreviation: "SHP",
    symbol: "£",
  },
  {
    currency: "Saudi Arabia Riyal",
    abbreviation: "SAR",
    symbol: "﷼",
  },
  {
    currency: "Serbia Dinar",
    abbreviation: "RSD",
    symbol: "Дин.",
  },
  {
    currency: "Seychelles Rupee",
    abbreviation: "SCR",
    symbol: "₨",
  },
  {
    currency: "Singapore Dollar",
    abbreviation: "SGD",
    symbol: "$",
  },
  {
    currency: "Solomon Islands Dollar",
    abbreviation: "SBD",
    symbol: "$",
  },
  {
    currency: "Somalia Shilling",
    abbreviation: "SOS",
    symbol: "S",
  },
  {
    currency: "South Africa Rand",
    abbreviation: "ZAR",
    symbol: "R",
  },
  {
    currency: "Korea (South) Won",
    abbreviation: "KRW",
    symbol: "₩",
  },
  {
    currency: "Sri Lanka Rupee",
    abbreviation: "LKR",
    symbol: "₨",
  },
  {
    currency: "Sweden Krona",
    abbreviation: "SEK",
    symbol: "kr",
  },
  {
    currency: "Switzerland Franc",
    abbreviation: "CHF",
    symbol: "CHF",
  },
  {
    currency: "Suriname Dollar",
    abbreviation: "SRD",
    symbol: "$",
  },
  {
    currency: "Syria Pound",
    abbreviation: "SYP",
    symbol: "£",
  },
  {
    currency: "Taiwan New Dollar",
    abbreviation: "TWD",
    symbol: "NT$",
  },
  {
    currency: "Thailand Baht",
    abbreviation: "THB",
    symbol: "฿",
  },
  {
    currency: "Trinidad and Tobago Dollar",
    abbreviation: "TTD",
    symbol: "TT$",
  },
  {
    currency: "Turkey Lira",
    abbreviation: "TRY",
    symbol: "₺",
  },
  {
    currency: "Tuvalu Dollar",
    abbreviation: "TVD",
    symbol: "$",
  },
  {
    currency: "Ukraine Hryvna",
    abbreviation: "UAH",
    symbol: "₴",
  },
  {
    currency: "United Kingdom Pound",
    abbreviation: "GBP",
    symbol: "£",
  },
  {
    currency: "United Arab Emirates Dirham",
    abbreviation: "Dirham",
    symbol: "د.إ",
  },
  {
    currency: "United States Dollar",
    abbreviation: "USD",
    symbol: "$",
  },
  {
    currency: "Uruguay Peso",
    abbreviation: "UYU",
    symbol: "$U",
  },
  {
    currency: "Uzbekistan Som",
    abbreviation: "UZS",
    symbol: "лв",
  },
  {
    currency: "Venezuela Bolivar",
    abbreviation: "VEF",
    symbol: "Bs",
  },
  {
    currency: "Viet Nam Dong",
    abbreviation: "VND",
    symbol: "₫",
  },
  {
    currency: "Yemen Rial",
    abbreviation: "YER",
    symbol: "﷼",
  },
  {
    currency: "Zimbabwe Dollar",
    abbreviation: "ZWD",
    symbol: "Z$",
  },
];
export const Cryptocurrency = [
  {
    name: "Bitcoin",
    currency: "BTC",
  },
  {
    name: "Ethereum",
    currency: "ETH",
  },
  {
    name: "Tether",
    currency: "USDT",
  },
  // {
  //   name:"USD Coin",
  //   currency: "USDC",
  // },
  {
    name: "BNB",
    currency: "BNB",
  },
  {
    name: "Binance USD",
    currency: "BUSD",
  },
  {
    name: "XRP",
    currency: "XRP",
  },
  {
    name: "Cardano",
    currency: "ADA",
  },
  {
    name: "Solana",
    currency: "SOL",
  },
  {
    name: "Dogecoin",
    currency: "DOGE",
  },
  {
    name: "Polkadot",
    currency: "DOT",
  },
  {
    name: "Polygon",
    currency: "MATIC",
  },
];
export const CountryCodewithEmoji = [
  {
    name: "Afghanistan",
    dial_code: "+93",
    emoji: "🇦🇫",
    code: "AF",
    currency: "Afghanistan Afghani",
    abbreviation: "AFN",
    symbol: "؋",
  },
  {
    name: "Aland Islands",
    dial_code: "+358",
    emoji: "🇦🇽",
    code: "AX",
    currency: "Euro",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Albania",
    dial_code: "+355",
    emoji: "🇦🇱",
    code: "AL",
    currency: "Albania Lek",
    abbreviation: "ALL",
    symbol: "Lek",
  },
  {
    name: "Algeria",
    dial_code: "+213",
    emoji: "🇩🇿",
    code: "DZ",
    currency: "Algerian Dinar",
    abbreviation: "DZD",
    symbol: "دج",
  },
  {
    name: "AmericanSamoa",
    dial_code: "+1684",
    emoji: "🇦🇸",
    code: "AS",
    currency: "Samoa Tala",
    abbreviation: "AS",
    symbol: "WS$",
  },
  {
    name: "Andorra",
    dial_code: "+376",
    emoji: "🇦🇩",
    code: "AD",
    currency: "Euro",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Angola",
    dial_code: "+244",
    emoji: "🇦🇴",
    code: "AO",
    currency: "Angolan Kwanza",
    abbreviation: "AOA",
    symbol: "Kz",
    
  },
  {
    name: "Anguilla",
    dial_code: "+1264",
    emoji: "🇦🇮",
    code: "AI",
    currency: "Eastern Caribbean dollar",
    abbreviation: "XCD",
    symbol: "EC$",
  },
  {
    name: "Antarctica",
    dial_code: "+672",
    emoji: "🇦🇶",
    code: "AQ",
    currency: "Antarctican dollar",
    abbreviation: "AQ",
    symbol: "AC$",
  },
  {
    name: "Antigua and Barbuda",
    dial_code: "+1268",
    emoji: "🇦🇬",
    code: "AG",
    currency: "East Caribbean Dollar",
    abbreviation: "XCD",
    symbol: "EC$",
  },
  {
    name: "Argentina",
    dial_code: "+54",
    emoji: "🇦🇷",
    code: "AR",
    currency: "Argentine Peso",
    abbreviation: "ARS",
    symbol: "$",
  },
  {
    name: "Armenia",
    dial_code: "+374",
    emoji: "🇦🇲",
    code: "AM",
    currency: "Armenian Dram",
    abbreviation: "AMD",
    symbol: "֏",
  },
  {
    name: "Aruba",
    dial_code: "+297",
    emoji: "🇦🇼",
    code: "AW",
    currency: "Aruba Guilder",
    abbreviation: "AWG",
    symbol: "ƒ",
  },
  {
    name: "Australia",
    dial_code: "+61",
    emoji: "🇦🇺",
    code: "AU",
    currency: "Australia Dollar",
    abbreviation: "AUD",
    symbol: "$",
  },
  {
    name: "Austria",
    dial_code: "+43",
    emoji: "🇦🇹",
    code: "AT",
    currency: "Austrian Schilling",
    abbreviation: "EUR",
    symbol: "öS",
  },
  {
    name: "Azerbaijan",
    dial_code: "+994",
    emoji: "🇦🇿",
    code: "AZ",
    currency: "Azerbaijan New Manat",
    abbreviation: "AZN",
    symbol: "ман",
  },
  {
    name: "Bahamas",
    dial_code: "+1242",
    emoji: "🇧🇸",
    code: "BS",
    currency: "Bahamas Dollar",
    abbreviation: "BSD",
    symbol: "$",
  },
  {
    name: "Bahrain",
    dial_code: "+973",
    emoji: "🇧🇭",
    code: "BH",
    currency: "Bahrain Dinar",
    abbreviation: "BHD",
    symbol: ".د.ب",
  },
  {
    name: "Bangladesh",
    dial_code: "+880",
    emoji: "🇧🇩",
    code: "BD",
    currency: " Bangladeshi Taka",
    abbreviation: "BDT",
    symbol: "৳",
  },
  {
    name: "Barbados",
    dial_code: "+1246",
    emoji: "🇧🇧",
    code: "BB",
    currency: "Barbados Dollar",
    abbreviation: "BBD",
    symbol: "$",
  },
  {
    name: "Belarus",
    dial_code: "+375",
    emoji: "🇧🇾",
    code: "BY",
    currency: "Belarus Ruble",
    abbreviation: "BYN",
    symbol: "p.",
  },
  {
    name: "Belgium",
    dial_code: "+32",
    emoji: "🇧🇪",
    code: "BE",
    currency: "EURO",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Belize",
    dial_code: "+501",
    emoji: "🇧🇿",
    code: "BZ",
    currency: "Belize Dollar",
    abbreviation: "BZD",
    symbol: "BZ$",
  },
  {
    name: "Benin",
    dial_code: "+229",
    emoji: "🇧🇯",
    code: "BJ",
    currency: "West African CFA franc",
    abbreviation: "XOF",
    symbol: "CFA",
  },
  {
    name: "Bermuda",
    dial_code: "+1441",
    emoji: "🇧🇲",
    code: "BM",
    currency: "Bermuda Dollar",
    abbreviation: "BMD",
    symbol: "$",
  },
  {
    name: "Bhutan",
    dial_code: "+975",
    emoji: "🇧🇹",
    code: "BT",
    currency: "Bhutanese Ngultrum",
    abbreviation: "BTN",
    symbol: "Nu.",
  },
  {
    name: "Bolivia, Plurinational State of",
    dial_code: "+591",
    emoji: "🇧🇴",
    code: "BO",
    currency: "Bolivian boliviano",
    abbreviation: "BO",
    symbol: "Bs",
  },
  {
    name: "Bosnia and Herzegovina",
    dial_code: "+387",
    emoji: "🇧🇦",
    code: "BA",
    currency: "Bosnia and Herzegovina Convertible Marka",
    abbreviation: "BAM",
    symbol: "KM",
  },
  {
    name: "Botswana",
    dial_code: "+267",
    emoji: "🇧🇼",
    code: "BW",
    currency: "Botswana Pula",
    abbreviation: "BWP",
    symbol: "P",
  },
  {
    name: "Brazil",
    dial_code: "+55",
    emoji: "🇧🇷",
    code: "BR",
    currency: "Brazil Real",
    abbreviation: "BRL",
    symbol: "R$",
  },
  {
    name: "British Indian Ocean Territory",
    dial_code: "+246",
    emoji: "🇮🇴",
    code: "IO",
    currency: "United States Dollar",
    abbreviation: "USD",
    symbol: "$",
  },
  {
    name: "Brunei Darussalam",
    dial_code: "+673",
    emoji: "🇧🇳",
    code: "BN",
    currency: "Brunei Darussalam Dollar",
    abbreviation: "BND",
    symbol: "$",
  },
  {
    name: "Bulgaria",
    dial_code: "+359",
    emoji: "🇧🇬",
    code: "BG",
    currency: "Bulgaria Lev",
    abbreviation: "BGN",
    symbol: "лв",
  },
  {
    name: "Burkina Faso",
    dial_code: "+226",
    emoji: "🇧🇫",
    code: "BF",
    currency: "West African CFA franc",
    abbreviation: "XOF",
    symbol: "F CFA",
  },
  {
    name: "Burundi",
    dial_code: "+257",
    emoji: "🇧🇮",
    code: "BI",
    currency: "Burundian Franc",
    abbreviation: "BIF",
    symbol: "FBu",
  },
  {
    name: "Cambodia",
    dial_code: "+855",
    emoji: "🇰🇭",
    code: "KH",
    currency: "Cambodia Riel",
    abbreviation: "KHR",
    symbol: "៛",
  },
  {
    name: "Cameroon",
    dial_code: "+237",
    emoji: "🇨🇲",
    code: "CM",
    currency: "Central African CFA franc",
    abbreviation: "XAF",
    symbol: "FCFA",
  },
  {
    name: "Canada",
    dial_code: "+1",
    emoji: "🇨🇦",
    code: "CA",
    currency: "Canada Dollar",
    abbreviation: "CAD",
    symbol: "$",
  },
  {
    name: "Cape Verde",
    dial_code: "+238",
    emoji: "🇨🇻",
    code: "CV",
    currency: "Cape Verde Escudo",
    abbreviation: "CV",
    symbol: "Esc",
  },
  {
    name: "Cayman Islands",
    dial_code: "+ 345",
    emoji: "🇰🇾",
    code: "KY",
    currency: "Cayman Islands Dollar",
    abbreviation: "KYD",
    symbol: "$",
  },
  {
    name: "Central African Republic",
    dial_code: "+236",
    emoji: "🇨🇫",
    code: "CF",
    currency: "Central African CFA franc",
    abbreviation: "XAF",
    symbol: "F CFA",
  },
  {
    name: "Chad",
    dial_code: "+235",
    emoji: "🇹🇩",
    code: "TD",
    currency: "Central African CFA franc",
    abbreviation: "XAF",
    symbol: "F CFA",
  },
  {
    name: "Chile",
    dial_code: "+56",
    emoji: "🇨🇱",
    code: "CL",
    currency: "Chile Peso",
    abbreviation: "CLP",
    symbol: "$",
  },
  {
    name: "China",
    dial_code: "+86",
    emoji: "🇨🇳",
    code: "CN",
    currency: "China Yuan Renminbi",
    abbreviation: "CNY",
    symbol: "¥",
  },
  {
    name: "Christmas Island",
    dial_code: "+61",
    emoji: "🇨🇽",
    code: "CX",
    currency: "the Australian dollar",
    abbreviation: "AUD",
    symbol: "$",
  },
  {
    name: "Cocos (Keeling) Islands",
    dial_code: "+61",
    emoji: "🇨🇨",
    code: "CC",
    currency: "the Australian dollar",
    abbreviation: "AUD",
    symbol: "$",
  },
  {
    name: "Colombia",
    dial_code: "+57",
    emoji: "🇨🇴",
    code: "CO",
    currency: "Colombia Peso",
    abbreviation: "COP",
    symbol: "$",
  },
  {
    name: "Comoros",
    dial_code: "+269",
    emoji: "🇰🇲",
    code: "KM",
    currency: "Comorian Franc",
    abbreviation: "KMF",
    symbol: "CF",
  },
  {
    name: "Congo",
    dial_code: "+242",
    emoji: "🇨🇬",
    code: "CG",
    currency: " Congolese Franc",
    abbreviation: "CG",
    symbol: "FC",
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dial_code: "+243",
    emoji: "🇨🇩",
    code: "CD",
    currency: " Congolese Franc",
    abbreviation: "CDF",
    symbol: "FC",
  },
  {
    name: "Cook Islands",
    dial_code: "+682",
    emoji: "🇨🇰",
    code: "CK",
    currency: "New Zealand Dollar",
    abbreviation: "NZD",
    symbol: "$",
  },
  {
    name: "Costa Rica",
    dial_code: "+506",
    emoji: "🇨🇷",
    code: "CR",
    currency: "Costa Rica Colon",
    abbreviation: "CRC",
    symbol: "₡",
  },
  {
    name: "Cote d'Ivoire",
    dial_code: "+225",
    emoji: "🇨🇮",
    code: "CI",
    currency: "West African CFA franc",
    abbreviation: "XOF",
    symbol: "F CFA",
  },
  {
    name: "Croatia",
    dial_code: "+385",
    emoji: "🇭🇷",
    code: "HR",
    currency: "Croatia Kuna",
    abbreviation: "HRK",
    symbol: "kn",
  },
  {
    name: "Cuba",
    dial_code: "+53",
    emoji: "🇨🇺",
    code: "CU",
    currency: "Cuba Peso",
    abbreviation: "CUP",
    symbol: "₱",
  },
  {
    name: "Cyprus",
    dial_code: "+357",
    emoji: "🇨🇾",
    code: "CY",
    currency: "EURO",
    abbreviation: "EUR",
    symbol: "Cyprus",
  },
  {
    name: "Czech Republic",
    dial_code: "+420",
    emoji: "🇨🇿",
    code: "CZ",
    currency: "Czech Republic Koruna",
    abbreviation: "CZK",
    symbol: "Kč",
  },
  {
    name: "Denmark",
    dial_code: "+45",
    emoji: "🇩🇰",
    code: "DK",
    currency: "Denmark Krone",
    abbreviation: "DKK",
    symbol: "kr",
  },
  {
    name: "Djibouti",
    dial_code: "+253",
    emoji: "🇩🇯",
    code: "DJ",
    currency: "Djiboutian Franc",
    abbreviation: "DJF",
    symbol: "Fdj",
  },
  {
    name: "Dominica",
    dial_code: "+1767",
    emoji: "🇩🇲",
    code: "DM",
    currency: "Dominican Peso",
    abbreviation: "DOP",
    symbol: "RD$",
  },
  {
    name: "Dominican Republic",
    dial_code: "+1849",
    emoji: "🇩🇴",
    code: "DO",
    currency: "Dominican Republic Peso",
    abbreviation: "DOP",
    symbol: "RD$", 
  },
  {
    name: "Ecuador",
    dial_code: "+593",
    emoji: "🇪🇨",
    code: "EC",
    currency: "United States Dollar",
    abbreviation: "USD",
    symbol: "$", 
  },
  {
    name: "Egypt",
    dial_code: "+20",
    emoji: "🇪🇬",
    code: "EG",
    currency: "Egypt Pound",
    abbreviation: "EGP",
    symbol: "£",
  },
  {
    name: "El Salvador",
    dial_code: "+503",
    emoji: "🇸🇻",
    code: "SV",
    currency: "El Salvador Colon",
    abbreviation: "SVC",
    symbol: "$",
  },
  {
    name: "Equatorial Guinea",
    dial_code: "+240",
    emoji: "🇬🇶",
    code: "GQ",
    currency: "Central African CFA franc",
    abbreviation: "XAF",
    symbol: "FCFA",
  },
  {
    name: "Eritrea",
    dial_code: "+291",
    emoji: "🇪🇷",
    code: "ER",
    currency: "the Nakfa",
    abbreviation: "ERN",
    symbol: "Nfk",
  },
  {
    name: "Estonia",
    dial_code: "+372",
    emoji: "🇪🇪",
    code: "EE",
    currency: "Estonia Kroon",
    abbreviation: "EEK",
    symbol: "kr",
  },
  {
    name: "Ethiopia",
    dial_code: "+251",
    emoji: "🇪🇹",
    code: "ET",
    currency: "Ethiopian Birr",
    abbreviation: "ETB",
    symbol: "ብር",
  },
  {
    name: "Falkland Islands (Malvinas)",
    dial_code: "+500",
    emoji: "🇫🇰",
    code: "FK",
    currency: "Falkland Islands (Malvinas) Pound",
    abbreviation: "FKP",
    symbol: "£",
  },
  {
    name: "Faroe Islands",
    dial_code: "+298",
    emoji: "🇫🇴",
    code: "FO",
    currency: "Danish Krone",
    abbreviation: "DKK",
    symbol: "kr",
  },
  {
    name: "Fiji",
    dial_code: "+679",
    emoji: "🇫🇯",
    code: "FJ",
    currency: "Fiji Dollar",
    abbreviation: "FJD",
    symbol: "$",
  },
  {
    name: "Finland",
    dial_code: "+358",
    emoji: "🇫🇮",
    code: "FI",
    currency: "Euro",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "France",
    dial_code: "+33",
    emoji: "🇫🇷",
    code: "FR",
    currency: "Euro",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "French Guiana",
    dial_code: "+594",
    emoji: "🇬🇫",
    code: "GF",
    currency: "Euro",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "French Polynesia",
    dial_code: "+689",
    emoji: "🇵🇫",
    code: "PF",
    currency: "CFP Franc",
    abbreviation: "XPF",
    symbol: "F",
  },
  {
    name: "Gabon",
    dial_code: "+241",
    emoji: "🇬🇦",
    code: "GA",
    currency: "Central African CFA franc",
    abbreviation: "XAF",
    symbol: "FCFA",
  },
  {
    name: "Gambia",
    dial_code: "+220",
    emoji: "🇬🇲",
    code: "GM",
    currency: "Gambian Dalasi",
    abbreviation: "GMD",
    symbol: "D",
  },
  {
    name: "Georgia",
    dial_code: "+995",
    emoji: "🇬🇪",
    code: "GE",
    currency: "Georgian Lari",
    abbreviation: "GEL",
    symbol: "GEL",
  },
  {
    name: "Germany",
    dial_code: "+49",
    emoji: "🇩🇪",
    code: "DE",
    currency: " Euro",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Ghana",
    dial_code: "+233",
    emoji: "🇬🇭",
    code: "GH",
    currency: "Ghana Cedis",
    abbreviation: "GHS",
    symbol: "¢",
  },
  {
    name: "Gibraltar",
    dial_code: "+350",
    emoji: "🇬🇮",
    code: "GI",
    currency: "Gibraltar Pound",
    abbreviation: "GIP",
    symbol: "£",
  },
  {
    name: "Greece",
    dial_code: "+30",
    emoji: "🇬🇷",
    code: "GR",
    currency: "EURO",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Greenland",
    dial_code: "+299",
    emoji: "🇬🇱",
    code: "GL",
    currency: "Danish Krone",
    abbreviation: "DKK",
    symbol: "KR.",
  },
  {
    name: "Grenada",
    dial_code: "+1473",
    emoji: "🇬🇩",
    code: "GD",
    currency: "East Caribbean Dollar",
    abbreviation: "XCD",
    symbol: "$",
  },
  {
    name: "Guadeloupe",
    dial_code: "+590",
    emoji: "🇬🇵",
    code: "GP",
    currency: "EURO",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Guam",
    dial_code: "+1671",
    emoji: "🇬🇺",
    code: "GU",
    currency: "United States Dollar",
    abbreviation: "USD",
    symbol: "$",
  },
  {
    name: "Guatemala",
    dial_code: "+502",
    emoji: "🇬🇹",
    code: "GT",
    currency: "Guatemala Quetzal",
    abbreviation: "GTQ",
    symbol: "Q",
  },
  {
    name: "Guernsey",
    dial_code: "+44",
    emoji: "🇬🇬",
    code: "GG",
    currency: "Guernsey Pound",
    abbreviation: "GBP",
    symbol: "£",
  },
  {
    name: "Guinea",
    dial_code: "+224",
    emoji: "🇬🇳",
    code: "GN",
    currency: "Guinean Franc",
    abbreviation: "GNF",
    symbol: "GFr",
  },
  {
    name: "Guinea-Bissau",
    dial_code: "+245",
    emoji: "🇬🇼",
    code: "GW",
    currency: "West African CFA franc",
    abbreviation: "XOF",
    symbol: "F CFA",
  },
  {
    name: "Guyana",
    dial_code: "+595",
    emoji: "🇬🇾",
    code: "GY",
    currency: "Guyana Dollar",
    abbreviation: "GYD",
    symbol: "$",
  },
  {
    name: "Haiti",
    dial_code: "+509",
    emoji: "🇭🇹",
    code: "HT",
    currency: "Haitian Gourde",
    abbreviation: "HTG",
    symbol: "G",
  },
  {
    name: "Holy See (Vatican City State)",
    dial_code: "+379",
    emoji: "🇻🇦",
    code: "VA",
    currency: "Euro",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Honduras",
    dial_code: "+504",
    emoji: "🇭🇳",
    code: "HN",
    currency: "Honduras Lempira",
    abbreviation: "HNL",
    symbol: "L",
  },
  {
    name: "Hong Kong",
    dial_code: "+852",
    emoji: "🇭🇰",
    code: "HK",
    currency: "Hong Kong Dollar",
    abbreviation: "HKD",
    symbol: "$",
  },
  {
    name: "Hungary",
    dial_code: "+36",
    emoji: "🇭🇺",
    code: "HU",
    currency: "Hungary Forint",
    abbreviation: "HUF",
    symbol: "Ft",
  },
  {
    name: "Iceland",
    dial_code: "+354",
    emoji: "🇮🇸",
    code: "IS",
    currency: "Iceland Krona",
    abbreviation: "ISK",
    symbol: "kr",
  },
  {
    name: "India",
    dial_code: "+91",
    emoji: "🇮🇳",
    code: "IN",
    currency: "India Rupee",
    abbreviation: "INR",
    symbol: "₹",
  },
  {
    name: "Indonesia",
    dial_code: "+62",
    emoji: "🇮🇩",
    code: "ID",
    currency: "Indonesia Rupiah",
    abbreviation: "IDR",
    symbol: "Rp",
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    dial_code: "+98",
    emoji: "🇮🇷",
    code: "IR",
    currency: "Iran Rial",
    abbreviation: "IRR",
    symbol: "﷼",
  },
  {
    name: "Iraq",
    dial_code: "+964",
    emoji: "🇮🇷",
    code: "IQ",
    currency: "Iraqi Dinar",
    abbreviation: "IQD",
    symbol: "ع.د",
  },
  {
    name: "Ireland",
    dial_code: "+353",
    emoji: "🇮🇪",
    code: "IE",
    currency: "EURO",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Isle of Man",
    dial_code: "+44",
    emoji: "🇮🇲",
    code: "IM",
    currency: "Isle of Man Pound",
    abbreviation: "GBP",
    symbol: "£",
  },
  {
    name: "Israel",
    dial_code: "+972",
    emoji: "🇮🇱",
    code: "IL",
    currency: "Israel Shekel",
    abbreviation: "ILS",
    symbol: "₪",
  },
  {
    name: "Italy",
    dial_code: "+39",
    emoji: "🇮🇹",
    code: "IT",
    currency: "Euro",
    abbreviation: "EUR",
    symbol: "₤",
  },
  {
    name: "Jamaica",
    dial_code: "+1876",
    emoji: "🇯🇲",
    code: "JM",
    currency: "Jamaica Dollar",
    abbreviation: "JMD",
    symbol: "J$",
  },
  {
    name: "Japan",
    dial_code: "+81",
    emoji: "🇯🇵",
    code: "JP",
    currency: "Japan Yen",
    abbreviation: "JPY",
    symbol: "¥",
  },
  {
    name: "Jersey",
    dial_code: "+44",
    emoji: "🇯🇪",
    code: "JE",
    currency: "Jersey Pound",
    abbreviation: "GBP",
    symbol: "£",
  },
  {
    name: "Jordan",
    dial_code: "+962",
    emoji: "🇯🇴",
    code: "JO",
    currency: "Jordanian Dinar",
    abbreviation: "JOD",
    symbol: " د.أ",
  },
  {
    name: "Kazakhstan",
    dial_code: "+77",
    emoji: "🇰🇿",
    code: "KZ",
    currency: "Kazakhstan Tenge",
    abbreviation: "KZT",
    symbol: "лв",
  },
  {
    name: "Kenya",
    dial_code: "+254",
    emoji: "🇰🇪",
    code: "KE",
    currency: "Kenyan Shilling",
    abbreviation: "KES",
    symbol: "лв",
  },
  {
    name: "Kiribati",
    dial_code: "+686",
    emoji: "🇰🇮",
    code: "KI",
    currency: "Kiribati dollar",
    abbreviation: "KI",
    symbol: "$",
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: "+850",
    emoji: "🇰🇵",
    code: "KP",
    currency: "North Korean Won",
    abbreviation: "KPW",
    symbol: "₩",
  },
  {
    name: "Korea, Republic of South Korea",
    dial_code: "+82",
    emoji: "🇰🇷",
    code: "KR",
    currency: "Korea (South) Won",
    abbreviation: "KRW",
    symbol: "₩",
  },
  {
    name: "Kuwait",
    dial_code: "+965",
    emoji: "🇰🇼",
    code: "KW",
    currency: "Kuwaiti Dinar ",
    abbreviation: "KWD",
    symbol: "د.ك",
  },
  {
    name: "Kyrgyzstan",
    dial_code: "+996",
    emoji: "🇰🇬",
    code: "KG",
    currency: "Kyrgyzstan Som",
    abbreviation: "KGS",
    symbol: "лв",
  },
  {
    name: "Laos",
    dial_code: "+856",
    emoji: "🇱🇦",
    code: "LA",
    currency: "Laos Kip",
    abbreviation: "LAK",
    symbol: "₭",
  },
  {
    name: "Latvia",
    dial_code: "+371",
    emoji: "🇱🇻",
    code: "LV",
    currency: "Latvia Lat",
    abbreviation: "LVL",
    symbol: "Ls",
  },
  {
    name: "Lebanon",
    dial_code: "+961",
    emoji: "🇱🇧",
    code: "LB",
    currency: "Lebanon Pound",
    abbreviation: "LBP",
    symbol: "£",
  },
  {
    name: "Lesotho",
    dial_code: "+266",
    emoji: "🇱🇸",
    code: "LS",
    currency: "Lesotho Loti",
    abbreviation: "LSL",
    symbol: "pl.",
  },
  {
    name: "Liberia",
    dial_code: "+231",
    emoji: "🇱🇷",
    code: "LR",
    currency: "Liberia Dollar",
    abbreviation: "LRD",
    symbol: "$",
  },
  {
    name: "Libyan Arab Jamahiriya",
    dial_code: "+218",
    emoji: "🇱🇾",
    code: "LY",
    currency: "Libyan Dinar",
    abbreviation: "LY",
    symbol: "ل.د",
  },
  {
    name: "Liechtenstein",
    dial_code: "+423",
    emoji: "🇱🇮",
    code: "LI",
    currency: "Swiss Franc",
    abbreviation: "CHF",
    symbol: " SFr.",
  },
  {
    name: "Lithuania",
    dial_code: "+370",
    emoji: "🇱🇹",
    code: "LT",
    currency: "Lithuania Litas",
    abbreviation: "EUR",
    symbol: "Lt",
  },
  {
    name: "Luxembourg",
    dial_code: "+352",
    emoji: "🇱🇺",
    code: "LU",
    currency: "Luxembourgian Franc",
    abbreviation: "EUR",
    symbol: "fr.",
  },
  {
    name: "Macao",
    dial_code: "+853",
    emoji: "🇲🇴",
    code: "MO",
    currency: "Macanese Pataca",
    abbreviation: "MOP",
    symbol: "MOP$",
  },
  {
    name: "Macedonia",
    dial_code: "+389",
    emoji: "🇲🇰",
    code: "MK",
    currency: "Macedonia Denar",
    abbreviation: "MKD",
    symbol: "ден",
  },
  {
    name: "Madagascar",
    dial_code: "+261",
    emoji: "🇲🇬",
    code: "MG",
    currency: "Malagasy Ariary",
    abbreviation: "MGA",
    symbol: "Ar",
  },
  {
    name: "Malawi",
    dial_code: "+265",
    emoji: "🇲🇼",
    code: "MW",
    currency: "Malawian Kwacha ",
    abbreviation: "MWK",
    symbol: "MK",
  },
  {
    name: "Malaysia",
    dial_code: "+60",
    emoji: "🇲🇾",
    code: "MY",
    currency: "Malaysia Ringgit",
    abbreviation: "MYR",
    symbol: "RM",
  },
  {
    name: "Maldives",
    dial_code: "+960",
    emoji: "🇲🇻",
    code: "MV",
    currency: "Maldivian Rufiyaa",
    abbreviation: "MVR",
    symbol: ".ރ",
  },
  {
    name: "Mali",
    dial_code: "+223",
    emoji: "🇲🇱",
    code: "ML",
    currency: "West African CFA franc",
    abbreviation: "SOS",
    symbol: "F CFA",
  },
  {
    name: "Malta",
    dial_code: "+356",
    emoji: "🇲🇹",
    code: "MT",
    currency: "EURO",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Marshall Islands",
    dial_code: "+692",
    emoji: "🇲🇭",
    code: "MH",
    currency: "United States Dollar",
    abbreviation: "USD",
    symbol: "$",
  },
  {
    name: "Martinique",
    dial_code: "+596",
    emoji: "🇲🇶",
    code: "MQ",
    currency: "Euro",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Mauritania",
    dial_code: "+222",
    emoji: "🇲🇷",
    code: "MR",
    currency: " Mauritanian Ouguiya ",
    abbreviation: "MRU",
    symbol: "MRU",
  },
  {
    name: "Mauritius",
    dial_code: "+230",
    emoji: "🇲🇺",
    code: "MU",
    currency: "Mauritius Rupee",
    abbreviation: "MUR",
    symbol: "₨",
  },
  {
    name: "Mayotte",
    dial_code: "+262",
    emoji: "🇾🇹",
    code: "YT",
    currency: "EURO",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Mexico",
    dial_code: "+52",
    emoji: "🇲🇽",
    code: "MX",
    currency: "Mexico Peso",
    abbreviation: "MXN",
    symbol: "$",
  },
  {
    name: "Micronesia, Federated States of Micronesia",
    dial_code: "+691",
    emoji: "🇫🇲",
    code: "FM",
    currency: "United States Dollar",
    abbreviation: "USD",
    symbol: "$",
  },
  {
    name: "Moldova",
    dial_code: "+373",
    emoji: "🇲🇩",
    code: "MD",
    currency: "Moldovan Leu",
    abbreviation: "MDL",
    symbol: "L",
  },
  {
    name: "Monaco",
    dial_code: "+377",
    emoji: "🇲🇨",
    code: "MC",
    currency: "Euro",
    abbreviation: "EUR",
    symbol: "	€",
  },
  {
    name: "Mongolia",
    dial_code: "+976",
    emoji: "🇲🇳",
    code: "MN",
    currency: "Mongolian Tugrik",
    abbreviation: "MNT",
    symbol: " ₮",
  },
  {
    name: "Montenegro",
    dial_code: "+382",
    emoji: "🇲🇪",
    code: "ME",
    currency: "Euro",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Montserrat",
    dial_code: "+1664",
    emoji: "🇲🇸",
    code: "MS",
    currency: "East Caribbean Dollar",
    abbreviation: "XCD",
    symbol: "EC$",
  },
  {
    name: "Morocco",
    dial_code: "+212",
    emoji: "🇲🇦",
    code: "MA",
    currency: "Moroccan Dirham",
    abbreviation: "MAD",
    symbol: "MAD",
  },
  {
    name: "Mozambique",
    dial_code: "+258",
    emoji: "🇲🇿",
    code: "MZ",
    currency: "Mozambique Metical",
    abbreviation: "MZN",
    symbol: "MT",
  },
  {
    name: "Myanmar",
    dial_code: "+95",
    emoji: "🇲🇲",
    code: "MM",
    currency: "Myanmar Kyat",
    abbreviation: "MMK",
    symbol: "K",
  },
  {
    name: "Namibia",
    emoji: "🇳🇦",
    dial_code: "+264",
    code: "NA",
    currency: "Namibia Dollar",
    abbreviation: "NAD",
    symbol: "$",
  },
  {
    name: "Nauru",
    dial_code: "+674",
    emoji: "🇳🇷",
    code: "NR",
    currency: "Australian Dollar",
    abbreviation: "AUD",
    symbol: "AU$",
  },
  {
    name: "Nepal",
    dial_code: "+977",
    emoji: "🇳🇵",
    code: "NP",
    currency: "Nepal Rupee",
    abbreviation: "NPR",
    symbol: "₨",
  },
  {
    name: "Netherlands",
    dial_code: "+31",
    emoji: "🇳🇱",
    code: "NL",
    currency: "Netherlands Antilles Guilder",
    abbreviation: "ANG",
    symbol: "ƒ",
  },
  {
    name: "Netherlands Antilles",
    dial_code: "+599",
    emoji: "🇧🇶",
    code: "AN",
    currency: "Netherlands Antilles Guilder",
    abbreviation: "ANG",
    symbol: "ƒ",
  },
  {
    name: "New Caledonia",
    dial_code: "+687",
    emoji: "🇳🇨",
    code: "NC",
    currency: "CFP Franc",
    abbreviation: "XPF",
    symbol: "F",
  },
  {
    name: "New Zealand",
    dial_code: "+64",
    emoji: "🇳🇿",
    code: "NZ",
    currency: "New Zealand Dollar",
    abbreviation: "NZD",
    symbol: "$",
  },
  {
    name: "Nicaragua",
    dial_code: "+505",
    emoji: "🇳🇮",
    code: "NI",
    currency: "Nicaragua Cordoba",
    abbreviation: "NIO",
    symbol: "C$",
  },
  {
    name: "Niger",
    dial_code: "+227",
    emoji: "🇳🇪",
    code: "NE",
    currency: "West African CFA franc",
    abbreviation: "XOF",
    symbol: "F CFA",
  },
  {
    name: "Nigeria",
    dial_code: "+234",
    emoji: "🇳🇬",
    code: "NG",
    currency: "Nigeria Naira",
    abbreviation: "NGN",
    symbol: "₦",
  },
  {
    name: "Niue",
    dial_code: "+683",
    emoji: "🇳🇺",
    code: "NU",
    currency: "New Zealand Dollar",
    abbreviation: "NZD",
    symbol: "NZ$",
  },
  {
    name: "Norfolk Island",
    dial_code: "+672",
    emoji: "🇳🇫",
    code: "NF",
    currency: "Australian dollar",
    abbreviation: "AUD",
    symbol: "AU$",
  },
  {
    name: "Northern Mariana Islands",
    dial_code: "+1670",
    emoji: "🇲🇵",
    code: "MP",
    currency: "United States Dollar",
    abbreviation: "USD",
    symbol: "$",
  },
  {
    name: "Norway",
    dial_code: "+47",
    emoji: "🇳🇴",
    code: "NO",
    currency: "Norway Krone",
    abbreviation: "NOK",
    symbol: "kr",
  },
  {
    name: "Oman",
    dial_code: "+968",
    emoji: "🇴🇲",
    code: "OM",
    currency: "Oman Rial",
    abbreviation: "OMR",
    symbol: "﷼",
  },
  {
    name: "Pakistan",
    dial_code: "+92",
    emoji: "🇵🇰",
    code: "PK",
    currency: "Pakistan Rupee",
    abbreviation: "PKR",
    symbol: "₨",
  },
  {
    name: "Palau",
    dial_code: "+680",
    emoji: "🇵🇼",
    code: "PW",
    currency: "United States Dollar",
    abbreviation: "USD",
    symbol: "$",
  },
  {
    name: "Palestinian Territory, Occupied",
    dial_code: "+970",
    emoji: "🇵🇸",
    code: "PS",
    currency: "Israeli Shekel",
    abbreviation: "PS",
    symbol: "₪",
  },
  {
    name: "Panama",
    dial_code: "+507",
    emoji: "🇵🇦",
    code: "PA",
    currency: "Panama Balboa",
    abbreviation: "PAB",
    symbol: "B/.",
  },
  {
    name: "Papua New Guinea",
    dial_code: "+675",
    emoji: "🇵🇬",
    code: "PG",
    currency: "Papua New Guinean Kina",
    abbreviation: "PGK",
    symbol: "PGK",
  },
  {
    name: "Paraguay",
    dial_code: "+595",
    emoji: "🇵🇾",
    code: "PY",
    currency: "Paraguay Guarani",
    abbreviation: "PYG",
    symbol: "Gs",
  },
  {
    name: "Peru",
    dial_code: "+51",
    emoji: "🇵🇪",
    code: "PE",
    currency: "Peru Nuevo Sol",
    abbreviation: "PEN",
    symbol: "S/.",
  },
  {
    name: "Philippines",
    dial_code: "+63",
    emoji: "🇵🇭",
    code: "PH",
    currency: "Philippines Peso",
    abbreviation: "PHP",
    symbol: "₱",
  },
  {
    name: "Pitcairn",
    dial_code: "+872",
    emoji: "🇵🇳",
    code: "PN",
    currency: "New Zealand Dollar",
    abbreviation: "NZD",
    symbol: "NZ$",
  },
  {
    name: "Poland",
    dial_code: "+48",
    emoji: "🇵🇱",
    code: "PL",
    currency: "Poland Zloty",
    abbreviation: "PLN",
    symbol: "zł",
  },
  {
    name: "Portugal",
    dial_code: "+351",
    emoji: "🇵🇹",
    code: "PT",
    currency: "EURO",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Puerto Rico",
    dial_code: "+1939",
    emoji: "🇵🇷",
    code: "PR",
    currency: " United States dollar",
    abbreviation: "USD",
    symbol: "$",
  },
  {
    name: "Qatar",
    dial_code: "+974",
    emoji: "🇶🇦",
    code: "QA",
    currency: "Qatar Riyal",
    abbreviation: "QAR",
    symbol: "﷼",
  },
  {
    name: "Romania",
    dial_code: "+40",
    emoji: "🇷🇴",
    code: "RO",
    currency: "Romania New Leu",
    abbreviation: "RON",
    symbol: "lei",
  },
  {
    name: "Russia",
    dial_code: "+7",
    emoji: "🇷🇺",
    code: "RU",
    currency: "Russia Ruble",
    abbreviation: "RUB",
    symbol: "руб",
  },
  {
    name: "Rwanda",
    dial_code: "+250",
    emoji: "🇷🇼",
    code: "RW",
    currency: "Rwandan Franc",
    abbreviation: "RW",
    symbol: "RF",
  },
  {
    name: "Reunion",
    dial_code: "+262",
    emoji: "🇷🇪",
    code: "RE",
    currency: "EURO",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Saint Barthelemy",
    dial_code: "+590",
    emoji: "🇧🇱",
    code: "BL",
    currency: "EURO",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dial_code: "+290",
    emoji: "🇸🇭",
    code: "SH",
    currency: "Helena Pound",
    abbreviation: "SHP",
    symbol: "£",
  },
  {
    name: "Saint Kitts and Nevis",
    dial_code: "+1869",
    emoji: "🇰🇳",
    code: "KN",
    currency: "East Caribbean Dollar",
    abbreviation: "XCD",
    symbol: "EC$",
  },
  {
    name: "Saint Lucia",
    dial_code: "+1758",
    emoji: "🇱🇨",
    code: "LC",
    currency: "East Caribbean Dollar",
    abbreviation: "XCD",
    symbol: "EC$",
  },
  {
    name: "Saint Martin",
    dial_code: "+590",
    emoji: "🇲🇫",
    code: "MF",
    currency: "EURO",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Saint Pierre and Miquelon",
    dial_code: "+508",
    emoji: "🇵🇲",
    code: "PM",
    currency: "EURO",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Saint Vincent and the Grenadines",
    dial_code: "+1784",
    emoji: "🇻🇨",
    code: "VC",
    currency: "East Caribbean Dollar",
    abbreviation: "XCD",
    symbol: "ES$",
  },
  {
    name: "Samoa",
    dial_code: "+685",
    emoji: "🇼🇸",
    code: "WS",
    currency: "Samoan Tala",
    abbreviation: "WST",
    symbol: "WS$",
  },
  {
    name: "San Marino",
    dial_code: "+378",
    emoji: "🇸🇲",
    code: "SM",
    currency: "Euro",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Sao Tome and Principe",
    dial_code: "+239",
    emoji: "🇸🇹",
    code: "ST",
    currency: "São Tomé and Príncipe dobra",
    abbreviation: "STN",
    symbol: "STD",
  },
  {
    name: "Saudi Arabia",
    dial_code: "+966",
    emoji: "🇸🇦",
    code: "SA",
    currency: "Saudi Arabia Riyal",
    abbreviation: "SAR",
    symbol: "﷼",
  },
  {
    name: "Senegal",
    dial_code: "+221",
    emoji: "🇸🇳",
    code: "SN",
    currency: "West African CFA franc",
    abbreviation: "XOF",
    symbol: "F CFA",
  },
  {
    name: "Serbia",
    dial_code: "+381",
    emoji: "🇷🇸",
    code: "RS",
    currency: "Serbia Dinar",
    abbreviation: "RSD",
    symbol: "Дин.",
  },
  {
    name: "Seychelles",
    dial_code: "+248",
    emoji: "🇸🇨",
    code: "SC",
    currency: "Seychelles Rupee",
    abbreviation: "SCR",
    symbol: "₨",
  },
  {
    name: "Sierra Leone",
    dial_code: "+232",
    emoji: "🇸🇱",
    code: "SL",
    currency: "leone",
    abbreviation: "SLE",
    symbol: "Le",
  },
  {
    name: "Singapore",
    dial_code: "+65",
    emoji: "🇸🇬",
    code: "SG",
    currency: "Singapore Dollar",
    abbreviation: "SGD",
    symbol: "$",
  },
  {
    name: "Slovakia",
    dial_code: "+421",
    emoji: "🇸🇰",
    code: "SK",
    currency: "Euro",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Slovenia",
    dial_code: "+386",
    emoji: "🇸🇮",
    code: "SI",
    currency: "Euro",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Solomon Islands",
    dial_code: "+677",
    emoji: "🇸🇧",
    code: "SB",
    currency: "Solomon Islands Dollar",
    abbreviation: "SBD",
    symbol: "$",
  },
  {
    name: "Somalia",
    dial_code: "+252",
    emoji: "🇸🇴",
    code: "SO",
    currency: "Somalia Shilling",
    abbreviation: "SOS",
    symbol: "S",
  },
  {
    name: "South Africa",
    dial_code: "+27",
    emoji: "🇿🇦",
    code: "ZA",
    currency: "South Africa Rand",
    abbreviation: "ZAR",
    symbol: "R",
  },
  {
    name: "South Sudan",
    dial_code: "+211",
    emoji: "🇸🇸",
    code: "SS",
    currency: "South Sudanese Pound",
    abbreviation: "SSP",
    symbol: "£",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    dial_code: "+500",
    emoji: "🇬🇸",
    code: "GS",
    currency: "Pound sterling",
    abbreviation: "GS",
    symbol: "£",
  },
  {
    name: "Spain",
    dial_code: "+34",
    emoji: "🇪🇸",
    code: "ES",
    currency: "Euro",
    abbreviation: "EUR",
    symbol: "€",
  },
  {
    name: "Sri Lanka",
    dial_code: "+94",
    emoji: "🇱🇰",
    code: "LK",
    currency: "Sri Lanka Rupee",
    abbreviation: "LKR",
    symbol: "₨",
  },
  {
    name: "Sudan",
    dial_code: "+249",
    emoji: "🇸🇩",
    code: "SD",
    currency: "Sudanese pound",
    abbreviation: "SDG",
    symbol: "ج.س.",
  },
  {
    name: "Suriname",
    dial_code: "+597",
    emoji: "🇸🇷",
    code: "SR",
    currency: "Suriname Dollar",
    abbreviation: "SRD",
    symbol: "$",
  },
  {
    name: "Svalbard and Jan Mayen",
    dial_code: "+47",
    emoji: "🇸🇯",
    code: "SJ",
    currency: "Norwegian krone ",
    abbreviation: "NOK",
    symbol: "NOK",
  },
  {
    name: "Swaziland",
    dial_code: "+268",
    emoji: "🇸🇿",
    code: "SZ",
    currency: "Swazi Lilangeni",
    abbreviation: "SZL",
    symbol: " L",
  },
  {
    name: "Sweden",
    dial_code: "+46",
    emoji: "🇸🇪",
    code: "SE",
    currency: "Sweden Krona",
    abbreviation: "SEK",
    symbol: "kr",
  },
  {
    name: "Switzerland",
    dial_code: "+41",
    emoji: "🇨🇭",
    code: "CH",
    currency: "Switzerland Franc",
    abbreviation: "CHF",
    symbol: "CHF",
  },
  {
    name: "Syrian Arab Republic",
    dial_code: "+963",
    emoji: "🇸🇾",
    code: "SY",
    currency: "Syrian Pounds",
    abbreviation: "SYP",
    symbol: "SYP",
  },
  {
    name: "Taiwan",
    dial_code: "+886",
    emoji: "🇹🇼",
    code: "TW",
    currency: "Taiwan New Dollar",
    abbreviation: "TWD",
    symbol: "NT$",
  },
  {
    name: "Tajikistan",
    dial_code: "+992",
    emoji: "🇹🇯",
    code: "TJ",
    currency: "Tajikistani Somoni",
    abbreviation: "TJS",
    symbol: "ЅM",
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    dial_code: "+255",
    emoji: "🇹🇿",
    code: "TZ",
    currency: "Tanzanian Shilling",
    abbreviation: "TZS",
    symbol: "TSh",
  },
  {
    name: "Thailand",
    dial_code: "+66",
    emoji: "🇹🇭",
    code: "TH",
    currency: "Thailand Baht",
    abbreviation: "THB",
    symbol: "฿",
  },
  {
    name: "Timor-Leste",
    dial_code: "+670",
    emoji: "🇹🇱",
    code: "TL",
    currency: "United States Dollar",
    abbreviation: "USD",
    symbol: "$",
  },
  {
    name: "Togo",
    dial_code: "+228",
    emoji: "🇹🇬",
    code: "TG",
    currency: "West African CFA franc",
    abbreviation: "XOF",
    symbol: "F.CFA",
  },
  {
    name: "Tokelau",
    dial_code: "+690",
    emoji: "🇹🇰",
    code: "TK",
    currency: "New Zealand Dollar",
    abbreviation: "NZD",
    symbol: "NZ$",
  },
  {
    name: "Tonga",
    dial_code: "+676",
    emoji: "🇹🇴",
    code: "TO",
    currency: "Tongan Paʻanga",
    abbreviation: "TOP",
    symbol: "T$",
  },
  {
    name: "Trinidad and Tobago",
    dial_code: "+1868",
    emoji: "🇹🇹",
    code: "TT",
    currency: "Trinidad and Tobago Dollar",
    abbreviation: "TTD",
    symbol: "TT$",
  },
  {
    name: "Tunisia",
    dial_code: "+216",
    emoji: "🇹🇳",
    code: "TN",
    currency: "Tunisian Dinar",
    abbreviation: "TND",
    symbol: "د.ت",
  },
  {
    name: "Turkey",
    dial_code: "+90",
    emoji: "🇹🇷",
    code: "TR",
    currency: "Turkey Lira",
    abbreviation: "TRY",
    symbol: "₺",
  },
  {
    name: "Turkmenistan",
    dial_code: "+993",
    emoji: "🇹🇲",
    code: "TM",
    currency: "Turkmenistani Manat",
    abbreviation: "TMT",
    symbol: "T",
  },
  {
    name: "Turks and Caicos Islands",
    dial_code: "+1649",
    emoji: "🇹🇨",
    code: "TC",
    currency: "United States Dollar",
    abbreviation: "USD",
    symbol: "$",
  },
  {
    name: "Tuvalu",
    dial_code: "+688",
    emoji: "🇹🇻",
    code: "TV",
    currency: "Australian Dollar",
    abbreviation: "AUD",
    symbol: "$",
  },
  {
    name: "Uganda",
    dial_code: "+256",
    emoji: "🇺🇬",
    code: "UG",
    currency: "Ugandan Shilling",
    abbreviation: "UGX",
    symbol: "USH",
  },
  {
    name: "Ukraine",
    dial_code: "+380",
    emoji: "🇺🇦",
    code: "UA",
    currency: "Ukraine Hryvna",
    abbreviation: "UAH",
    symbol: "₴",
  },
  {
    name: "United Arab Emirates",
    dial_code: "+971",
    emoji: "🇦🇪",
    code: "AE",
    currency: "United Arab Emirates Dirham",
    abbreviation: "AED",
    symbol: "د.إ",
  },
  {
    name: "United Kingdom",
    dial_code: "+44",
    emoji: "🇬🇧",
    code: "GB",
    currency: "United Kingdom Pound",
    abbreviation: "GBP",
    symbol: "£",
  },
  {
    name: "United States",
    dial_code: "+1",
    emoji: "🇺🇸",
    code: "US",
    currency: "United States Dollar",
    abbreviation: "USD",
    symbol: "$",
  },
  {
    name: "Uruguay",
    dial_code: "+598",
    emoji: "🇺🇾",
    code: "UY",
    currency: "Uruguay Peso",
    abbreviation: "UYI",
    symbol: "$U",
  },
  {
    name: "Uzbekistan",
    dial_code: "+998",
    emoji: "🇺🇿",
    code: "UZ",
    currency: "Uzbekistan Som",
    abbreviation: "UZS",
    symbol: "лв",
  },
  {
    name: "Vanuatu",
    dial_code: "+678",
    emoji: "🇻🇺",
    code: "VU",
    currency: "Vanuatu Vatu",
    abbreviation: "VUV",
    symbol: "VT",
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    dial_code: "+58",
    emoji: "🇻🇪",
    code: "VE",
    currency: "Venezuelan bolívar",
    abbreviation: "VE",
    symbol: "BS.F.",
  },
  {
    name: "Vietnam",
    dial_code: "+84",
    emoji: "🇻🇳",
    code: "VN",
    currency: "Vietnamese dong",
    abbreviation: "VN",
    symbol: "₫",
  },
  {
    name: "Virgin Islands, British",
    dial_code: "+1284",
    emoji: "🇻🇬",
    code: "VG",
    currency: "United States Dollar",
    abbreviation: "USD",
    symbol: "$",
  },
  {
    name: "Virgin Islands, U.S.",
    dial_code: "+1340",
    emoji: "🇻🇮",
    code: "VI",
    currency: "United States Dollar",
    abbreviation: "USD",
    symbol: "$",
  },
  {
    name: "Wallis and Futuna",
    dial_code: "+681",
    emoji: "🇼🇫",
    code: "WF",
    currency: "CFP Franc",
    abbreviation: "XPF",
    symbol: "CFPF",
  },
  {
    name: "Yemen",
    dial_code: "+967",
    emoji: "🇾🇪",
    code: "YE",
    currency: "Yemen Rial",
    abbreviation: "YER",
    symbol: "﷼",
  },
  {
    name: "Zambia",
    dial_code: "+260",
    emoji: "🇿🇲",
    code: "ZM",
    currency: "Zambian Kwacha",
    abbreviation: "ZMW",
    symbol: "ZK",
  },
  {
    name: "Zimbabwe",
    dial_code: "+263",
    emoji: "🇿🇼",
    code: "ZW",
    currency: "Zimbabwe Dollar",
    abbreviation: "ZWL",
    symbol: "Z$",
  },
];
